version: "3.3"
services:
  python-fastapi-app:
    container_name: python-fastapi-app
    build: 
      context: .
      dockerfile: dockerfiles/python-fastapi-app.Dockerfile
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always
    ports:
      - 8001:8000
    volumes:
      - ./python-fastapi-app:/code
  python-sanic-app:
    container_name: python-sanic-app
    build: 
      context: .
      dockerfile: dockerfiles/python-sanic-app.Dockerfile
    restart: always
    ports:
      - 8002:8000
    volumes:
      - ./python-sanic-app:/code
  python-starlette-app:
    container_name: python-starlette-app
    build: 
      context: .
      dockerfile: dockerfiles/python-starlette-app.Dockerfile
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always
    ports:
      - 8003:8000
    volumes:
      - ./python-starlette-app:/code
  python-blacksheep-app:
    container_name: python-blacksheep-app
    build: 
      context: .
      dockerfile: dockerfiles/python-blacksheep-app.Dockerfile
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always
    ports:
      - 8004:8000
    volumes:
      - ./python-blacksheep-app:/code
  python-tornado-app:
    container_name: python-tornado-app
    build: 
      context: .
      dockerfile: dockerfiles/python-tornado-app.Dockerfile
    restart: always
    ports:
      - 8005:8000
    volumes:
      - ./python-tornado-app:/code